name: CI

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Calq Flow (dry-run)
        uses: calq-framework/flow@latest
        with:
          subcommand: 'publish --dry-run'
        env: ${{ secrets }}
